### PR TITLE
Being able to highlight parenthesis even in literal string

### PR DESCRIPTION
**Pull request by YorkZ**
Hi Nikolaj Schumacher,

I've added a new feature to be able to highlight parenthesis in literal string. Can you merge my changes?

York

### CODE REVIEW

**Comment by tsdh** [comment]
Hi.  Sorry for the long delay.  I've just taken over maintainership.

I think I'd consider this PR.  Could you please rebase it onto the current HEAD so that I can easily try it out?

**Comment by tsdh** [comment]
@YorkZ Any news on the highlight-parentheses-in-strings front?

**Comment by nschum** [comment]
I don't think ignoring string delimiters is the right way to make this work.

Consider the following lisp examples:

    ((  ":)"   ))

Now the first parentheses will be matched with the one inside the string. (You might want that, but that definitely shouldn't be the default.)

Even worse:

    ((  ";)"   ))

Now the semicolon starts a comment and everything behind it isn't matched at all.

The right way to make this work would be to look at parentheses inside and outside strings separately: Find out if the point is inside a string (`syntax-ppss` will tell you) and use `scan-lists` to get the "raw" parentheses.

**Comment by tsdh** [comment]
@nschum I haven't tested this version, but obviously such a feature would need to be restricted to one string literal and not affect its surrounding.

**Pull request closed without merging**
